/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnergiaLoginRouteImport } from './routes/energia/login'
import { Route as EnergiaDashboardTarifarioRouteImport } from './routes/energia/dashboard/tarifario'
import { Route as EnergiaDashboardPanelRouteImport } from './routes/energia/dashboard/panel'
import { Route as EnergiaDashboardMonitoreoRouteImport } from './routes/energia/dashboard/monitoreo'
import { Route as EnergiaDashboardHomeRouteImport } from './routes/energia/dashboard/home'
import { Route as EnergiaDashboardDesbalanceRouteImport } from './routes/energia/dashboard/desbalance'
import { Route as EnergiaDashboardComparadorRouteImport } from './routes/energia/dashboard/comparador'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiaLoginRoute = EnergiaLoginRouteImport.update({
  id: '/energia/login',
  path: '/energia/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiaDashboardTarifarioRoute =
  EnergiaDashboardTarifarioRouteImport.update({
    id: '/energia/dashboard/tarifario',
    path: '/energia/dashboard/tarifario',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnergiaDashboardPanelRoute = EnergiaDashboardPanelRouteImport.update({
  id: '/energia/dashboard/panel',
  path: '/energia/dashboard/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiaDashboardMonitoreoRoute =
  EnergiaDashboardMonitoreoRouteImport.update({
    id: '/energia/dashboard/monitoreo',
    path: '/energia/dashboard/monitoreo',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnergiaDashboardHomeRoute = EnergiaDashboardHomeRouteImport.update({
  id: '/energia/dashboard/home',
  path: '/energia/dashboard/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiaDashboardDesbalanceRoute =
  EnergiaDashboardDesbalanceRouteImport.update({
    id: '/energia/dashboard/desbalance',
    path: '/energia/dashboard/desbalance',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnergiaDashboardComparadorRoute =
  EnergiaDashboardComparadorRouteImport.update({
    id: '/energia/dashboard/comparador',
    path: '/energia/dashboard/comparador',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/energia/login': typeof EnergiaLoginRoute
  '/energia/dashboard/comparador': typeof EnergiaDashboardComparadorRoute
  '/energia/dashboard/desbalance': typeof EnergiaDashboardDesbalanceRoute
  '/energia/dashboard/home': typeof EnergiaDashboardHomeRoute
  '/energia/dashboard/monitoreo': typeof EnergiaDashboardMonitoreoRoute
  '/energia/dashboard/panel': typeof EnergiaDashboardPanelRoute
  '/energia/dashboard/tarifario': typeof EnergiaDashboardTarifarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/energia/login': typeof EnergiaLoginRoute
  '/energia/dashboard/comparador': typeof EnergiaDashboardComparadorRoute
  '/energia/dashboard/desbalance': typeof EnergiaDashboardDesbalanceRoute
  '/energia/dashboard/home': typeof EnergiaDashboardHomeRoute
  '/energia/dashboard/monitoreo': typeof EnergiaDashboardMonitoreoRoute
  '/energia/dashboard/panel': typeof EnergiaDashboardPanelRoute
  '/energia/dashboard/tarifario': typeof EnergiaDashboardTarifarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/energia/login': typeof EnergiaLoginRoute
  '/energia/dashboard/comparador': typeof EnergiaDashboardComparadorRoute
  '/energia/dashboard/desbalance': typeof EnergiaDashboardDesbalanceRoute
  '/energia/dashboard/home': typeof EnergiaDashboardHomeRoute
  '/energia/dashboard/monitoreo': typeof EnergiaDashboardMonitoreoRoute
  '/energia/dashboard/panel': typeof EnergiaDashboardPanelRoute
  '/energia/dashboard/tarifario': typeof EnergiaDashboardTarifarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/energia/login'
    | '/energia/dashboard/comparador'
    | '/energia/dashboard/desbalance'
    | '/energia/dashboard/home'
    | '/energia/dashboard/monitoreo'
    | '/energia/dashboard/panel'
    | '/energia/dashboard/tarifario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/energia/login'
    | '/energia/dashboard/comparador'
    | '/energia/dashboard/desbalance'
    | '/energia/dashboard/home'
    | '/energia/dashboard/monitoreo'
    | '/energia/dashboard/panel'
    | '/energia/dashboard/tarifario'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/energia/login'
    | '/energia/dashboard/comparador'
    | '/energia/dashboard/desbalance'
    | '/energia/dashboard/home'
    | '/energia/dashboard/monitoreo'
    | '/energia/dashboard/panel'
    | '/energia/dashboard/tarifario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  EnergiaLoginRoute: typeof EnergiaLoginRoute
  EnergiaDashboardComparadorRoute: typeof EnergiaDashboardComparadorRoute
  EnergiaDashboardDesbalanceRoute: typeof EnergiaDashboardDesbalanceRoute
  EnergiaDashboardHomeRoute: typeof EnergiaDashboardHomeRoute
  EnergiaDashboardMonitoreoRoute: typeof EnergiaDashboardMonitoreoRoute
  EnergiaDashboardPanelRoute: typeof EnergiaDashboardPanelRoute
  EnergiaDashboardTarifarioRoute: typeof EnergiaDashboardTarifarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/login': {
      id: '/energia/login'
      path: '/energia/login'
      fullPath: '/energia/login'
      preLoaderRoute: typeof EnergiaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/dashboard/tarifario': {
      id: '/energia/dashboard/tarifario'
      path: '/energia/dashboard/tarifario'
      fullPath: '/energia/dashboard/tarifario'
      preLoaderRoute: typeof EnergiaDashboardTarifarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/dashboard/panel': {
      id: '/energia/dashboard/panel'
      path: '/energia/dashboard/panel'
      fullPath: '/energia/dashboard/panel'
      preLoaderRoute: typeof EnergiaDashboardPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/dashboard/monitoreo': {
      id: '/energia/dashboard/monitoreo'
      path: '/energia/dashboard/monitoreo'
      fullPath: '/energia/dashboard/monitoreo'
      preLoaderRoute: typeof EnergiaDashboardMonitoreoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/dashboard/home': {
      id: '/energia/dashboard/home'
      path: '/energia/dashboard/home'
      fullPath: '/energia/dashboard/home'
      preLoaderRoute: typeof EnergiaDashboardHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/dashboard/desbalance': {
      id: '/energia/dashboard/desbalance'
      path: '/energia/dashboard/desbalance'
      fullPath: '/energia/dashboard/desbalance'
      preLoaderRoute: typeof EnergiaDashboardDesbalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/dashboard/comparador': {
      id: '/energia/dashboard/comparador'
      path: '/energia/dashboard/comparador'
      fullPath: '/energia/dashboard/comparador'
      preLoaderRoute: typeof EnergiaDashboardComparadorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  EnergiaLoginRoute: EnergiaLoginRoute,
  EnergiaDashboardComparadorRoute: EnergiaDashboardComparadorRoute,
  EnergiaDashboardDesbalanceRoute: EnergiaDashboardDesbalanceRoute,
  EnergiaDashboardHomeRoute: EnergiaDashboardHomeRoute,
  EnergiaDashboardMonitoreoRoute: EnergiaDashboardMonitoreoRoute,
  EnergiaDashboardPanelRoute: EnergiaDashboardPanelRoute,
  EnergiaDashboardTarifarioRoute: EnergiaDashboardTarifarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
